/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as SystemsRouteImport } from './routes/systems'
import { Route as IntakeIndexRouteImport } from './routes/intake.index'
import { Route as IntakeClusterIdRouteImport } from './routes/intake.$clusterId'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as WorkWorkIdRouteImport } from './routes/work.$workId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsRoute = SystemsRouteImport.update({
  id: '/systems',
  path: '/systems',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeIndexRoute = IntakeIndexRouteImport.update({
  id: '/intake/',
  path: '/intake/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeClusterIdRoute = IntakeClusterIdRouteImport.update({
  id: '/intake/$clusterId',
  path: '/intake/$clusterId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkWorkIdRoute = WorkWorkIdRouteImport.update({
  id: '/work/$workId',
  path: '/work/$workId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRoute
  '/chat': typeof ChatRoute
  '/systems': typeof SystemsRoute
  '/intake/$clusterId': typeof IntakeClusterIdRoute
  '/work/$workId': typeof WorkWorkIdRoute
  '/intake/': typeof IntakeIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRoute
  '/chat': typeof ChatRoute
  '/systems': typeof SystemsRoute
  '/intake/$clusterId': typeof IntakeClusterIdRoute
  '/work/$workId': typeof WorkWorkIdRoute
  '/intake': typeof IntakeIndexRoute
  '/work': typeof WorkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRoute
  '/chat': typeof ChatRoute
  '/systems': typeof SystemsRoute
  '/intake/$clusterId': typeof IntakeClusterIdRoute
  '/work/$workId': typeof WorkWorkIdRoute
  '/intake/': typeof IntakeIndexRoute
  '/work/': typeof WorkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automations'
    | '/chat'
    | '/systems'
    | '/intake/$clusterId'
    | '/work/$workId'
    | '/intake/'
    | '/work/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automations'
    | '/chat'
    | '/systems'
    | '/intake/$clusterId'
    | '/work/$workId'
    | '/intake'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/automations'
    | '/chat'
    | '/systems'
    | '/intake/$clusterId'
    | '/work/$workId'
    | '/intake/'
    | '/work/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomationsRoute: typeof AutomationsRoute
  ChatRoute: typeof ChatRoute
  SystemsRoute: typeof SystemsRoute
  IntakeClusterIdRoute: typeof IntakeClusterIdRoute
  WorkWorkIdRoute: typeof WorkWorkIdRoute
  IntakeIndexRoute: typeof IntakeIndexRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems': {
      id: '/systems'
      path: '/systems'
      fullPath: '/systems'
      preLoaderRoute: typeof SystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/': {
      id: '/intake/'
      path: '/intake'
      fullPath: '/intake/'
      preLoaderRoute: typeof IntakeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/$clusterId': {
      id: '/intake/$clusterId'
      path: '/intake/$clusterId'
      fullPath: '/intake/$clusterId'
      preLoaderRoute: typeof IntakeClusterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$workId': {
      id: '/work/$workId'
      path: '/work/$workId'
      fullPath: '/work/$workId'
      preLoaderRoute: typeof WorkWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomationsRoute: AutomationsRoute,
  ChatRoute: ChatRoute,
  SystemsRoute: SystemsRoute,
  IntakeClusterIdRoute: IntakeClusterIdRoute,
  WorkWorkIdRoute: WorkWorkIdRoute,
  IntakeIndexRoute: IntakeIndexRoute,
  WorkIndexRoute: WorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
